---
- name: Converge 17 Source
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    postgresql_version: 16
    postgresql_listen: "0.0.0.0"
    postgresql_databases:
    - name: odoo
      encoding: UTF-8
      extensions: []
      owner: odoo
      state: present
      schemas:
      - name: odoo
        state: present
    postgresql_users:
    - name: odoo
      password: odoo_secret
      state: present
      role_attr_flags: CREATEDB,NOSUPERUSER
      privileges:
      - database: odoo
        privs: "All"
        state: present
      hosts:
      - cidr: localhost
        database: odoo
        state: present
      - cidr: 0.0.0.0/0
        database: odoo
        state: present
    wkhtmltopdf_install_google_fonts: false
    odoo_release: 17
    odoo_source_install: true
    odoo_config:
    - key: admin_passwd
      value: "P@ssw0rd!"
    - key: db_host
      value: "localhost"
    - key: db_port
      value: "5432"
    - key: db_user
      value: "odoo"
    - key: db_password
      value: "odoo_secret"
    - key: default_productivity_apps
      value: "False"
    odoo_init_databases:
    - database: odoo
      language: de_DE
  roles:
  - role: andrelohmann.postgresql
  - role: andrelohmann.nodesource
  - role: andrelohmann.wkhtmltopdf
  tasks:
  - name: Include andrelohmann.odoo
    ansible.builtin.include_role:
      name: "andrelohmann.odoo"
...
