---

- name: APT | Install acl
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: true
    autoremove: true
    update_cache: true
    cache_valid_time: 3600
  vars:
    packages:
    - acl

- name: Stop odoo
  ansible.builtin.systemd:
    name: odoo
    state: stopped
  changed_when: false

- name: Set odoo binary to /usr/bin/odoo
  ansible.builtin.set_fact:
    odoo_binary: /usr/bin/odoo
  when: not odoo_source_install
  changed_when: false

- name: Set odoo binary to /opt/odoo/odoo__VERSION__/odoo-bin
  ansible.builtin.set_fact:
    odoo_binary: "/opt/odoo/odoo{{ odoo_release }}/odoo-bin"
  when: odoo_source_install
  changed_when: false

- name: Initialize database
  ansible.builtin.shell: "/usr/bin/python3 {{ odoo_binary }} --config /etc/odoo/odoo.conf --database {{ item.database }} --init base --load-language {{ item.language }} --without-demo all --stop-after-init"
  args:
    executable: /bin/bash
  become: true
  become_user: odoo
  with_items: "{{ odoo_init_databases }}"
  changed_when: false

- name: Systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: false

- name: Systemctl enable odoo
  ansible.builtin.systemd:
    name: odoo
    enabled: true
  changed_when: false

...
